#!/bin/bash

RUNLIST=(
	# daisy (snow)
	stable:linux-4.19.y:zImage:exynos:arm

	# hp 11 (spring)
	chromium:chromeos-3.8-fixes:zImage:chromeos-exynos5:arm-5.4.0-r4
	# ...try 5.4.0 on upstream
	stable:linux-4.14.y:zImage:exynos:arm-5.4.0-r4

	# parallella
	stable:linux-4.14.y:uImage:multi_v7:arm
	stable:linux-4.19.y:uImage:multi_v7:arm
)

for i in ${RUNLIST[*]}; do
	repo=$(awk -F: '{print$1}' <<<$i)
	branch=$(awk -F: '{print$2}' <<<$i)
	image=$(awk -F: '{print$3}' <<<$i)
	defconfig=$(awk -F: '{print$4}' <<<$i)
	version=$(awk -F: '{print$5}' <<<$i)

	docker run --rm -it \
		--mount "type=volume,source=$repo-$defconfig-$version-$branch,dst=/usr/src/linux" \
		applehq/crossdev:${version} \
		pull-build-kernel \
		-g https://xxoo.ws/kernel/${repo}.git/ \
		-b $branch \
		-i $image \
		-d $defconfig
done
