#!/bin/bash

set -e

for i in $(./gccv.py); do
	docker image build . --squash -t applehq/crossdev:arm-$i   --build-arg version=$i
	docker image build . --squash -t applehq/crossdev:avr-$i   --build-arg version=$i --build-arg tuple=avr
	docker image build . --squash -t applehq/crossdev:arm64-$i --build-arg version=$i --build-arg tuple=aarch64-unknown-linux-gnu --build-arg arch=arm64
done

docker tag applehq/crossdev:arm-$i   applehq/crossdev:arm
docker tag applehq/crossdev:avr-$i   applehq/crossdev:avr
docker tag applehq/crossdev:arm64-$i applehq/crossdev:arm64

docker image list
