#!/bin/bash

set -ex

Ximages=(
	amd64:systemd:stage3
	amd64:systemd:stage4
)

Aimages=(
	armv7a:hardfp:stage3
	armv7a:hardfp:stage4
)

for i in ${Ximages[*]}; do
	arch=$(cut -d: -f1 <<<"$i")
	build=$(cut -d: -f2 <<<"$i")
	stage=$(cut -d: -f3 <<<"$i")

	relative=$(curl -s "https://builds.os.0xdc.io/$arch/$build/latest-$stage-$arch-$build.txt")
	bdate=$(dirname "$relative")
	fullpath="https://builds.os.0xdc.io/$arch/$build/$relative"

	docker image import "$fullpath" "applehq/roflmaos-$stage:$arch-$bdate"
	docker image tag "applehq/roflmaos-$stage:$arch-$bdate" "applehq/roflmaos-$stage:$arch-latest"
done

for i in ${Aimages[*]}; do
	arch=$(cut -d: -f1 <<<"$i")
	build=$(cut -d: -f2 <<<"$i")
	stage=$(cut -d: -f3 <<<"$i")

	relative=$(curl -s "https://builds.os.0xdc.io/$arch/$build/latest-$stage-${arch}_${build}.txt")
	bdate=$(dirname "$relative")
	fullpath="https://builds.os.0xdc.io/$arch/$build/$relative"

	docker image import "$fullpath" "applehq/roflmaos-$stage:$arch-$bdate"
	docker image tag "applehq/roflmaos-$stage:$arch-$bdate" "applehq/roflmaos-$stage:$arch-latest"
done
