#!/bin/bash

set -ex

for i in amd64:systemd:stage3 amd64:systemd:stage4; do
	arch=$(cut -d: -f1 <<<"$i")
	build=$(cut -d: -f2 <<<"$i")
	stage=$(cut -d: -f3 <<<"$i")

	relative=$(curl -s "https://builds.roflmao.space/$arch/$build/latest-$stage-$arch-$build.txt")
	bdate=$(dirname "$relative")
	fullpath="https://builds.roflmao.space/$arch/$build/$relative"

	docker image import "$fullpath" "applehq/roflmaos-$stage:$arch-$bdate"
	docker image tag "applehq/roflmaos-$stage:$arch-$bdate" "applehq/roflmaos-$stage:$arch-latest"

	test "$arch" = "amd64" && \
	docker image tag "applehq/roflmaos-$stage:$arch-$bdate" "applehq/roflmaos-$stage:latest"
done
