#!/bin/bash

set -e

while getopts "b:i:d:g:" opt; do
	case $opt in
	b)
		BRANCH="$OPTARG"
		;;
	i)
		IMAGE="$OPTARG"
		;;
	d)
		DEFCONFIG="$OPTARG"
		;;
	g)
		GIT_REPO="$OPTARG"
		;;
	esac
done

SRCDIR=/usr/src/linux

if test -d $SRCDIR/.git; then
	pushd $SRCDIR
	git pull --ff-only $GIT_REPO $BRANCH
else
	if test "$BRANCH"; then
		git clone -b $BRANCH $GIT_REPO $SRCDIR --depth 1
	else
		git clone $GIT_REPO $SRCDIR --depth 1
	fi
	pushd $SRCDIR
fi

if test -x ./chromeos/scripts/prepareconfig; then
	./chromeos/scripts/prepareconfig $DEFCONFIG
	./scripts/config -d ERROR_ON_WARNING
else
	make ${DEFCONFIG}_defconfig
fi

### Enable Kernel Options
enable_opts=(
	SWAP
	SQUASHFS
	BTRFS_FS
	CEPH_FS
	IKCONFIG
	SECCOMP
	NAMESPACES
)
for i in ${enable_opts[*]}; do
	case "$i" in
	SWAP|IKCONFIG*|NAMESPACES|SECCOMP|BTRFS_FS)
			./scripts/config -e $i
			;;
	*)
		if egrep -q '^CONFIG_MODULES=y$' .config; then
			./scripts/config -m $i
		else
			./scripts/config -e $i
		fi
		;;
	esac
done
make olddefconfig
enable_opts2=(
	# These appear after enabling the previous set of options
	SQUASHFS_LZO
	SQUASHFS_XZ
	IKCONFIG_PROC
	CEPH_LIB_USE_DNS_RESOLVER
)
for i in ${enable_opts2[*]}; do
	./scripts/config -e $i
done

make $IMAGE dtbs LOADADDR=0x8000 -j$(nproc)
if grep -q CONFIG_MODULES=y .config; then
	make modules -j$(nproc)
	make INSTALL_MOD_PATH="$(pwd)/tar-install" modules_install
fi

for i in ${enable_opts[*]} ${enable_opts2[*]}; do
	grep "CONFIG_$i" .config
done
